# -*- coding: utf-8 -*-
"""code 8.pynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dz2lCdhBnCWpHI8OIzGOPiLqa71_XbxE
"""

a=4
b=3
sum=a+b
print ("sum of numbers:",sum)

def cal_sum(a,b):
  sum=a+b
  print(sum)


cal_sum(5,7)
cal_sum(8,9)

def print_hello():
  print("hello")


print_hello()

#average of 3 numbers
def cal_avg(a,b,c):
  average=(a+b+c)/3
  print(average)

cal_avg(5,7,8)

